-- AlterTable
ALTER TABLE "Attendance" ALTER COLUMN "date" SET DATA TYPE TEXT,
ALTER COLUMN "timeIn" SET DATA TYPE TEXT,
ALTER COLUMN "timeOut" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Leave" ALTER COLUMN "date" SET DATA TYPE TEXT,
ALTER COLUMN "timeIn" SET DATA TYPE TEXT,
ALTER COLUMN "timeOut" SET DATA TYPE TEXT;
